// <auto-generated/>
using ReactiveUI;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Globalization;
using System.Reactive.Subjects;
using System.Reactive.Disposables.Fluent;
namespace ProjectHub.Application.Localization;

/// <summary>
/// 本地化字符串包装类 - 由 T4 模板自动生成
/// 直接访问 ProjectHub.Resources.Strings 资源文件
/// </summary>
public class LocalizedStrings : ReactiveObject
{
    private readonly Subject<CultureInfo> _cultureChanged = new();
    private CultureInfo _currentCulture = CultureInfo.CurrentUICulture;

    public LocalizedStrings()
    {
        _cultureChanged
           .Subscribe(_ => this.RaisePropertyChanged(string.Empty))
           .DisposeWith(Disposables);
    }

    private CompositeDisposable Disposables { get; } = new();

    /// <summary>
    /// 文化变更通知流
    /// </summary>
    public IObservable<CultureInfo> CultureChanged => _cultureChanged;

    /// <summary>
    /// 当前文化信息
    /// </summary>
    public CultureInfo CurrentCulture => _currentCulture;

    /// <summary>
    /// 异步设置文化
    /// </summary>
    public Task SetCultureAsync(CultureInfo culture)
    {
        if (culture == null)
            throw new ArgumentNullException(nameof(culture));

        _currentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.CurrentCulture = culture;
        Thread.CurrentThread.CurrentUICulture = culture;
        Thread.CurrentThread.CurrentCulture = culture;
        ProjectHub.Resources.Strings.Strings.Culture = culture;
        _cultureChanged.OnNext(culture);
        return Task.CompletedTask;
    }

    /// <summary>
    /// 获取格式化的翻译文本 (支持占位符)
    /// </summary>
    public string GetFormatted(string key, params object[] args)
    {
        var value = this[key];
        try
        {
            return string.Format(_currentCulture, value, args);
        }
        catch (FormatException)
        {
            return value;
        }
    }

    /// <summary>
    /// 索引器 - 通过 key 获取翻译文本
    /// </summary>
    public string this[string key]
    {
        get
        {
            try
            {
                var value = ProjectHub.Resources.Strings.Strings.ResourceManager.GetString(key, _currentCulture);
                return value ?? $"[{key}]";
            }
            catch
            {
                return $"[{key}]";
            }
        }
    }
    public string Confirm => ProjectHub.Resources.Strings.Strings.Confirm;
    public string Cancel => ProjectHub.Resources.Strings.Strings.Cancel;
    public string Delete => ProjectHub.Resources.Strings.Strings.Delete;
    public string Save => ProjectHub.Resources.Strings.Strings.Save;
    public string Edit => ProjectHub.Resources.Strings.Strings.Edit;
    public string Close => ProjectHub.Resources.Strings.Strings.Close;
    public string Project_Create => ProjectHub.Resources.Strings.Strings.Project_Create;
    public string Project_Edit => ProjectHub.Resources.Strings.Strings.Project_Edit;
    public string Project_Delete => ProjectHub.Resources.Strings.Strings.Project_Delete;
    public string Project_Launch => ProjectHub.Resources.Strings.Strings.Project_Launch;
    public string Project_OpenFolder => ProjectHub.Resources.Strings.Strings.Project_OpenFolder;
    public string DeleteConfirm_Title => ProjectHub.Resources.Strings.Strings.DeleteConfirm_Title;
    public string DeleteConfirm_Message => ProjectHub.Resources.Strings.Strings.DeleteConfirm_Message;
    public string DeleteConfirm_Success => ProjectHub.Resources.Strings.Strings.DeleteConfirm_Success;
    public string Message_SaveSuccess => ProjectHub.Resources.Strings.Strings.Message_SaveSuccess;
    public string Message_SaveFailed => ProjectHub.Resources.Strings.Strings.Message_SaveFailed;
    public string Message_LoadFailed => ProjectHub.Resources.Strings.Strings.Message_LoadFailed;
    public string Group_Create => ProjectHub.Resources.Strings.Strings.Group_Create;
    public string Tag_Add => ProjectHub.Resources.Strings.Strings.Tag_Add;
    public string Tag_Remove => ProjectHub.Resources.Strings.Strings.Tag_Remove;
    public string Sidebar_WorkFolders => ProjectHub.Resources.Strings.Strings.Sidebar_WorkFolders;
    public string Sidebar_NewFolder => ProjectHub.Resources.Strings.Strings.Sidebar_NewFolder;
    public string Sidebar_Refresh => ProjectHub.Resources.Strings.Strings.Sidebar_Refresh;
    public string Sidebar_NewSubFolder => ProjectHub.Resources.Strings.Strings.Sidebar_NewSubFolder;
    public string Sidebar_DeleteFolder => ProjectHub.Resources.Strings.Strings.Sidebar_DeleteFolder;
    public string Sidebar_Recent => ProjectHub.Resources.Strings.Strings.Sidebar_Recent;
    public string Sidebar_Favorites => ProjectHub.Resources.Strings.Strings.Sidebar_Favorites;
    public string Sidebar_Workspaces => ProjectHub.Resources.Strings.Strings.Sidebar_Workspaces;
    public string Sidebar_DevProjects => ProjectHub.Resources.Strings.Strings.Sidebar_DevProjects;
    public string Sidebar_WebApp => ProjectHub.Resources.Strings.Strings.Sidebar_WebApp;
    public string Sidebar_MobileApp => ProjectHub.Resources.Strings.Strings.Sidebar_MobileApp;
    public string Sidebar_DesktopApp => ProjectHub.Resources.Strings.Strings.Sidebar_DesktopApp;
    public string Sidebar_Learning => ProjectHub.Resources.Strings.Strings.Sidebar_Learning;
    public string Sidebar_Tutorials => ProjectHub.Resources.Strings.Strings.Sidebar_Tutorials;
    public string Sidebar_EBooks => ProjectHub.Resources.Strings.Strings.Sidebar_EBooks;
    public string Sidebar_AllProjects => ProjectHub.Resources.Strings.Strings.Sidebar_AllProjects;
    public string Sidebar_TagSettings => ProjectHub.Resources.Strings.Strings.Sidebar_TagSettings;
    public string Header_Search => ProjectHub.Resources.Strings.Strings.Header_Search;
    public string Header_Language => ProjectHub.Resources.Strings.Strings.Header_Language;
    public string Header_Theme => ProjectHub.Resources.Strings.Strings.Header_Theme;
    public string Header_Settings => ProjectHub.Resources.Strings.Strings.Header_Settings;
    public string Status_Ready => ProjectHub.Resources.Strings.Strings.Status_Ready;
    public string Status_ProjectCount => ProjectHub.Resources.Strings.Strings.Status_ProjectCount;
    public string Status_FolderCount => ProjectHub.Resources.Strings.Strings.Status_FolderCount;
    public string Status_WorkspaceCount => ProjectHub.Resources.Strings.Strings.Status_WorkspaceCount;
    public string Status_TagCount => ProjectHub.Resources.Strings.Strings.Status_TagCount;
    public string Status_TaggedProjects => ProjectHub.Resources.Strings.Strings.Status_TaggedProjects;
    public string Folder_NamePlaceholder => ProjectHub.Resources.Strings.Strings.Folder_NamePlaceholder;
    public string Folder_InputLabel => ProjectHub.Resources.Strings.Strings.Folder_InputLabel;
    public string Folder_Error_EmptyName => ProjectHub.Resources.Strings.Strings.Folder_Error_EmptyName;
    public string Folder_Error_NameTooLong => ProjectHub.Resources.Strings.Strings.Folder_Error_NameTooLong;
    public string Folder_Error_InvalidChars => ProjectHub.Resources.Strings.Strings.Folder_Error_InvalidChars;
    public string ProjectDialog_Title => ProjectHub.Resources.Strings.Strings.ProjectDialog_Title;
    public string ProjectDialog_Title_Add => ProjectHub.Resources.Strings.Strings.ProjectDialog_Title_Add;
    public string ProjectDialog_Title_Edit => ProjectHub.Resources.Strings.Strings.ProjectDialog_Title_Edit;
    public string ProjectDialog_NameLabel => ProjectHub.Resources.Strings.Strings.ProjectDialog_NameLabel;
    public string ProjectDialog_PathLabel => ProjectHub.Resources.Strings.Strings.ProjectDialog_PathLabel;
    public string ProjectDialog_ProgramLabel => ProjectHub.Resources.Strings.Strings.ProjectDialog_ProgramLabel;
    public string ProjectDialog_IconLabel => ProjectHub.Resources.Strings.Strings.ProjectDialog_IconLabel;
    public string ProjectDialog_Error_EmptyName => ProjectHub.Resources.Strings.Strings.ProjectDialog_Error_EmptyName;
    public string ProjectDialog_Error_EmptyPath => ProjectHub.Resources.Strings.Strings.ProjectDialog_Error_EmptyPath;
    public string ProjectDialog_Error_EmptyProgram => ProjectHub.Resources.Strings.Strings.ProjectDialog_Error_EmptyProgram;
    public string ProjectDialog_Browse => ProjectHub.Resources.Strings.Strings.ProjectDialog_Browse;
    public string ProjectDialog_DescriptionLabel => ProjectHub.Resources.Strings.Strings.ProjectDialog_DescriptionLabel;
    public string ProjectDialog_Step1_SelectFile => ProjectHub.Resources.Strings.Strings.ProjectDialog_Step1_SelectFile;
    public string ProjectDialog_Step2_ProjectInfo => ProjectHub.Resources.Strings.Strings.ProjectDialog_Step2_ProjectInfo;
    public string ProjectDialog_Step3_Description => ProjectHub.Resources.Strings.Strings.ProjectDialog_Step3_Description;
    public string ProjectDialog_ResetIcon => ProjectHub.Resources.Strings.Strings.ProjectDialog_ResetIcon;
    public string Message_Success => ProjectHub.Resources.Strings.Strings.Message_Success;
    public string Message_ProjectCreated => ProjectHub.Resources.Strings.Strings.Message_ProjectCreated;
    public string Message_ProjectUpdated => ProjectHub.Resources.Strings.Strings.Message_ProjectUpdated;
    public string Message_ProjectDeleted => ProjectHub.Resources.Strings.Strings.Message_ProjectDeleted;
    public string Message_DeleteFailed => ProjectHub.Resources.Strings.Strings.Message_DeleteFailed;
}