// <auto-generated/>
using ProjectHub.Application.Interfaces;
using ReactiveUI;
using System.Reactive.Disposables;
using System.Reactive.Disposables.Fluent;

namespace ProjectHub.Application.Localization;

public class LocalizedStrings : ReactiveObject
{
    public LocalizedStrings(ILocalizationService loc)
    {
        loc.CultureChanged
           .Subscribe(_ => this.RaisePropertyChanged(string.Empty))
           .DisposeWith(Disposables);
    }

    private CompositeDisposable Disposables { get; } = new();
    public string Confirm => ProjectHub.Resources.Strings.Strings.Confirm;
    public string Cancel => ProjectHub.Resources.Strings.Strings.Cancel;
    public string Delete => ProjectHub.Resources.Strings.Strings.Delete;
    public string Save => ProjectHub.Resources.Strings.Strings.Save;
    public string Edit => ProjectHub.Resources.Strings.Strings.Edit;
    public string Close => ProjectHub.Resources.Strings.Strings.Close;
    public string Project_Create => ProjectHub.Resources.Strings.Strings.Project_Create;
    public string Project_Edit => ProjectHub.Resources.Strings.Strings.Project_Edit;
    public string Project_Delete => ProjectHub.Resources.Strings.Strings.Project_Delete;
    public string Project_Launch => ProjectHub.Resources.Strings.Strings.Project_Launch;
    public string Project_OpenFolder => ProjectHub.Resources.Strings.Strings.Project_OpenFolder;
    public string DeleteConfirm_Title => ProjectHub.Resources.Strings.Strings.DeleteConfirm_Title;
    public string DeleteConfirm_Message => ProjectHub.Resources.Strings.Strings.DeleteConfirm_Message;
    public string DeleteConfirm_Success => ProjectHub.Resources.Strings.Strings.DeleteConfirm_Success;
    public string Message_SaveSuccess => ProjectHub.Resources.Strings.Strings.Message_SaveSuccess;
    public string Message_SaveFailed => ProjectHub.Resources.Strings.Strings.Message_SaveFailed;
    public string Message_LoadFailed => ProjectHub.Resources.Strings.Strings.Message_LoadFailed;
    public string Group_Create => ProjectHub.Resources.Strings.Strings.Group_Create;
    public string Tag_Add => ProjectHub.Resources.Strings.Strings.Tag_Add;
    public string Tag_Remove => ProjectHub.Resources.Strings.Strings.Tag_Remove;
}