//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHub.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectHub.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除&quot;{0}&quot;吗？此操作不可恢复。 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm_Message {
            get {
                return ResourceManager.GetString("DeleteConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm_Success {
            get {
                return ResourceManager.GetString("DeleteConfirm_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("DeleteConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建分组 的本地化字符串。
        /// </summary>
        public static string Group_Create {
            get {
                return ResourceManager.GetString("Group_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        public static string Message_LoadFailed {
            get {
                return ResourceManager.GetString("Message_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string Message_SaveFailed {
            get {
                return ResourceManager.GetString("Message_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string Message_SaveSuccess {
            get {
                return ResourceManager.GetString("Message_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建项目 的本地化字符串。
        /// </summary>
        public static string Project_Create {
            get {
                return ResourceManager.GetString("Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除项目 的本地化字符串。
        /// </summary>
        public static string Project_Delete {
            get {
                return ResourceManager.GetString("Project_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑项目 的本地化字符串。
        /// </summary>
        public static string Project_Edit {
            get {
                return ResourceManager.GetString("Project_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动项目 的本地化字符串。
        /// </summary>
        public static string Project_Launch {
            get {
                return ResourceManager.GetString("Project_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string Project_OpenFolder {
            get {
                return ResourceManager.GetString("Project_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加标签 的本地化字符串。
        /// </summary>
        public static string Tag_Add {
            get {
                return ResourceManager.GetString("Tag_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除标签 的本地化字符串。
        /// </summary>
        public static string Tag_Remove {
            get {
                return ResourceManager.GetString("Tag_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📁 工作文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_WorkFolders {
            get {
                return ResourceManager.GetString("Sidebar_WorkFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_NewFolder {
            get {
                return ResourceManager.GetString("Sidebar_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Sidebar_Refresh {
            get {
                return ResourceManager.GetString("Sidebar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建子文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_NewSubFolder {
            get {
                return ResourceManager.GetString("Sidebar_NewSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_DeleteFolder {
            get {
                return ResourceManager.GetString("Sidebar_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近使用 的本地化字符串。
        /// </summary>
        public static string Sidebar_Recent {
            get {
                return ResourceManager.GetString("Sidebar_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_Favorites {
            get {
                return ResourceManager.GetString("Sidebar_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作空间 的本地化字符串。
        /// </summary>
        public static string Sidebar_Workspaces {
            get {
                return ResourceManager.GetString("Sidebar_Workspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发项目 的本地化字符串。
        /// </summary>
        public static string Sidebar_DevProjects {
            get {
                return ResourceManager.GetString("Sidebar_DevProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web 应用 的本地化字符串。
        /// </summary>
        public static string Sidebar_WebApp {
            get {
                return ResourceManager.GetString("Sidebar_WebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动应用 的本地化字符串。
        /// </summary>
        public static string Sidebar_MobileApp {
            get {
                return ResourceManager.GetString("Sidebar_MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面应用 的本地化字符串。
        /// </summary>
        public static string Sidebar_DesktopApp {
            get {
                return ResourceManager.GetString("Sidebar_DesktopApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学习资源 的本地化字符串。
        /// </summary>
        public static string Sidebar_Learning {
            get {
                return ResourceManager.GetString("Sidebar_Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编程教程 的本地化字符串。
        /// </summary>
        public static string Sidebar_Tutorials {
            get {
                return ResourceManager.GetString("Sidebar_Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子书 的本地化字符串。
        /// </summary>
        public static string Sidebar_EBooks {
            get {
                return ResourceManager.GetString("Sidebar_EBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有项目 的本地化字符串。
        /// </summary>
        public static string Sidebar_AllProjects {
            get {
                return ResourceManager.GetString("Sidebar_AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签设置 的本地化字符串。
        /// </summary>
        public static string Sidebar_TagSettings {
            get {
                return ResourceManager.GetString("Sidebar_TagSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索项目... 的本地化字符串。
        /// </summary>
        public static string Header_Search {
            get {
                return ResourceManager.GetString("Header_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📦 共 {0} 个项目 的本地化字符串。
        /// </summary>
        public static string Status_ProjectCount {
            get {
                return ResourceManager.GetString("Status_ProjectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📁 {0} 个文件夹 的本地化字符串。
        /// </summary>
        public static string Status_FolderCount {
            get {
                return ResourceManager.GetString("Status_FolderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🚀 {0} 个工作空间 的本地化字符串。
        /// </summary>
        public static string Status_WorkspaceCount {
            get {
                return ResourceManager.GetString("Status_WorkspaceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🏷️ {0} 个标签分类 的本地化字符串。
        /// </summary>
        public static string Status_TagCount {
            get {
                return ResourceManager.GetString("Status_TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签项目: {0} 的本地化字符串。
        /// </summary>
        public static string Status_TaggedProjects {
            get {
                return ResourceManager.GetString("Status_TaggedProjects", resourceCulture);
            }
        }
    }
}
