//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHub.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectHub.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除&quot;{0}&quot;吗？此操作不可恢复。 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm_Message {
            get {
                return ResourceManager.GetString("DeleteConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm_Success {
            get {
                return ResourceManager.GetString("DeleteConfirm_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("DeleteConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹名称不能为空 的本地化字符串。
        /// </summary>
        public static string Folder_Error_EmptyName {
            get {
                return ResourceManager.GetString("Folder_Error_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹名称不能包含特殊字符 (\ / : * ? &quot; &lt; &gt; |) 的本地化字符串。
        /// </summary>
        public static string Folder_Error_InvalidChars {
            get {
                return ResourceManager.GetString("Folder_Error_InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹名称不能超过 100 个字符 的本地化字符串。
        /// </summary>
        public static string Folder_Error_NameTooLong {
            get {
                return ResourceManager.GetString("Folder_Error_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹名称 的本地化字符串。
        /// </summary>
        public static string Folder_InputLabel {
            get {
                return ResourceManager.GetString("Folder_InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入文件夹名称 的本地化字符串。
        /// </summary>
        public static string Folder_NamePlaceholder {
            get {
                return ResourceManager.GetString("Folder_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建分组 的本地化字符串。
        /// </summary>
        public static string Group_Create {
            get {
                return ResourceManager.GetString("Group_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换语言 的本地化字符串。
        /// </summary>
        public static string Header_Language {
            get {
                return ResourceManager.GetString("Header_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索项目... 的本地化字符串。
        /// </summary>
        public static string Header_Search {
            get {
                return ResourceManager.GetString("Header_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Header_Settings {
            get {
                return ResourceManager.GetString("Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换主题 的本地化字符串。
        /// </summary>
        public static string Header_Theme {
            get {
                return ResourceManager.GetString("Header_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        public static string Message_LoadFailed {
            get {
                return ResourceManager.GetString("Message_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 &quot;{0}&quot; 创建成功！ 的本地化字符串。
        /// </summary>
        public static string Message_ProjectCreated {
            get {
                return ResourceManager.GetString("Message_ProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 &quot;{0}&quot; 更新成功！ 的本地化字符串。
        /// </summary>
        public static string Message_ProjectUpdated {
            get {
                return ResourceManager.GetString("Message_ProjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 &quot;{0}&quot; 已删除 的本地化字符串。
        /// </summary>
        public static string Message_ProjectDeleted {
            get {
                return ResourceManager.GetString("Message_ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string Message_DeleteFailed {
            get {
                return ResourceManager.GetString("Message_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string Message_SaveFailed {
            get {
                return ResourceManager.GetString("Message_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string Message_SaveSuccess {
            get {
                return ResourceManager.GetString("Message_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建项目 的本地化字符串。
        /// </summary>
        public static string Project_Create {
            get {
                return ResourceManager.GetString("Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除项目 的本地化字符串。
        /// </summary>
        public static string Project_Delete {
            get {
                return ResourceManager.GetString("Project_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑项目 的本地化字符串。
        /// </summary>
        public static string Project_Edit {
            get {
                return ResourceManager.GetString("Project_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动项目 的本地化字符串。
        /// </summary>
        public static string Project_Launch {
            get {
                return ResourceManager.GetString("Project_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string Project_OpenFolder {
            get {
                return ResourceManager.GetString("Project_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览... 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Browse {
            get {
                return ResourceManager.GetString("ProjectDialog_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目描述 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_DescriptionLabel {
            get {
                return ResourceManager.GetString("ProjectDialog_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入项目名称 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Error_EmptyName {
            get {
                return ResourceManager.GetString("ProjectDialog_Error_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择打开路径 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Error_EmptyPath {
            get {
                return ResourceManager.GetString("ProjectDialog_Error_EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择默认程序 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Error_EmptyProgram {
            get {
                return ResourceManager.GetString("ProjectDialog_Error_EmptyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目图标 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_IconLabel {
            get {
                return ResourceManager.GetString("ProjectDialog_IconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名称 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_NameLabel {
            get {
                return ResourceManager.GetString("ProjectDialog_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开路径 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_PathLabel {
            get {
                return ResourceManager.GetString("ProjectDialog_PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认程序 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_ProgramLabel {
            get {
                return ResourceManager.GetString("ProjectDialog_ProgramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_ResetIcon {
            get {
                return ResourceManager.GetString("ProjectDialog_ResetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 1：选择项目文件 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Step1_SelectFile {
            get {
                return ResourceManager.GetString("ProjectDialog_Step1_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 2：项目信息（可修改） 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Step2_ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectDialog_Step2_ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 3：项目描述 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Step3_Description {
            get {
                return ResourceManager.GetString("ProjectDialog_Step3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项目 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Title {
            get {
                return ResourceManager.GetString("ProjectDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项目 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Title_Add {
            get {
                return ResourceManager.GetString("ProjectDialog_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑项目 的本地化字符串。
        /// </summary>
        public static string ProjectDialog_Title_Edit {
            get {
                return ResourceManager.GetString("ProjectDialog_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有项目 的本地化字符串。
        /// </summary>
        public static string Sidebar_AllProjects {
            get {
                return ResourceManager.GetString("Sidebar_AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_DeleteFolder {
            get {
                return ResourceManager.GetString("Sidebar_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面应用 的本地化字符串。
        /// </summary>
        public static string Sidebar_DesktopApp {
            get {
                return ResourceManager.GetString("Sidebar_DesktopApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发项目 的本地化字符串。
        /// </summary>
        public static string Sidebar_DevProjects {
            get {
                return ResourceManager.GetString("Sidebar_DevProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子书 的本地化字符串。
        /// </summary>
        public static string Sidebar_EBooks {
            get {
                return ResourceManager.GetString("Sidebar_EBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_Favorites {
            get {
                return ResourceManager.GetString("Sidebar_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学习资源 的本地化字符串。
        /// </summary>
        public static string Sidebar_Learning {
            get {
                return ResourceManager.GetString("Sidebar_Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动应用 的本地化字符串。
        /// </summary>
        public static string Sidebar_MobileApp {
            get {
                return ResourceManager.GetString("Sidebar_MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_NewFolder {
            get {
                return ResourceManager.GetString("Sidebar_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建子文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_NewSubFolder {
            get {
                return ResourceManager.GetString("Sidebar_NewSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近使用 的本地化字符串。
        /// </summary>
        public static string Sidebar_Recent {
            get {
                return ResourceManager.GetString("Sidebar_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Sidebar_Refresh {
            get {
                return ResourceManager.GetString("Sidebar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签设置 的本地化字符串。
        /// </summary>
        public static string Sidebar_TagSettings {
            get {
                return ResourceManager.GetString("Sidebar_TagSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编程教程 的本地化字符串。
        /// </summary>
        public static string Sidebar_Tutorials {
            get {
                return ResourceManager.GetString("Sidebar_Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web 应用 的本地化字符串。
        /// </summary>
        public static string Sidebar_WebApp {
            get {
                return ResourceManager.GetString("Sidebar_WebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📁 工作文件夹 的本地化字符串。
        /// </summary>
        public static string Sidebar_WorkFolders {
            get {
                return ResourceManager.GetString("Sidebar_WorkFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作空间 的本地化字符串。
        /// </summary>
        public static string Sidebar_Workspaces {
            get {
                return ResourceManager.GetString("Sidebar_Workspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📁 {0} 个文件夹 的本地化字符串。
        /// </summary>
        public static string Status_FolderCount {
            get {
                return ResourceManager.GetString("Status_FolderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📦 共 {0} 个项目 的本地化字符串。
        /// </summary>
        public static string Status_ProjectCount {
            get {
                return ResourceManager.GetString("Status_ProjectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🏷️ {0} 个标签分类 的本地化字符串。
        /// </summary>
        public static string Status_TagCount {
            get {
                return ResourceManager.GetString("Status_TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签项目: {0} 的本地化字符串。
        /// </summary>
        public static string Status_TaggedProjects {
            get {
                return ResourceManager.GetString("Status_TaggedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🚀 {0} 个工作空间 的本地化字符串。
        /// </summary>
        public static string Status_WorkspaceCount {
            get {
                return ResourceManager.GetString("Status_WorkspaceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加标签 的本地化字符串。
        /// </summary>
        public static string Tag_Add {
            get {
                return ResourceManager.GetString("Tag_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除标签 的本地化字符串。
        /// </summary>
        public static string Tag_Remove {
            get {
                return ResourceManager.GetString("Tag_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加工作空间 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_Title_Add {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑工作空间 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_Title_Edit {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 1：基本信息 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_Step1_BasicInfo {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_Step1_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作空间名称 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_NameLabel {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述（可选） 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_DescriptionLabel {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 2：选择项目 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_Step2_SelectProjects {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_Step2_SelectProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_SelectAll {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消全选 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_DeselectAll {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 3：启动配置 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_Step3_LaunchConfig {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_Step3_LaunchConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用自定义启动顺序 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_UseCustomLaunchOrder {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_UseCustomLaunchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认启动间隔： 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_LaunchIntervalLabel {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_LaunchIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：设置项目启动之间的等待时间（秒），0 表示连续启动不等待 的本地化字符串。
        /// </summary>
        public static string WorkSpaceDialog_LaunchIntervalHint {
            get {
                return ResourceManager.GetString("WorkSpaceDialog_LaunchIntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建工作空间 的本地化字符串。
        /// </summary>
        public static string WorkSpace_Create {
            get {
                return ResourceManager.GetString("WorkSpace_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑工作空间 的本地化字符串。
        /// </summary>
        public static string WorkSpace_Edit {
            get {
                return ResourceManager.GetString("WorkSpace_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除工作空间 的本地化字符串。
        /// </summary>
        public static string WorkSpace_Delete {
            get {
                return ResourceManager.GetString("WorkSpace_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动所有项目 的本地化字符串。
        /// </summary>
        public static string WorkSpace_LaunchAll {
            get {
                return ResourceManager.GetString("WorkSpace_LaunchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作空间 "{0}" 创建成功！ 的本地化字符串。
        /// </summary>
        public static string Message_WorkSpaceCreated {
            get {
                return ResourceManager.GetString("Message_WorkSpaceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作空间 "{0}" 更新成功！ 的本地化字符串。
        /// </summary>
        public static string Message_WorkSpaceUpdated {
            get {
                return ResourceManager.GetString("Message_WorkSpaceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作空间 "{0}" 已删除 的本地化字符串。
        /// </summary>
        public static string Message_WorkSpaceDeleted {
            get {
                return ResourceManager.GetString("Message_WorkSpaceDeleted", resourceCulture);
            }
        }
    }
}
